monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main_nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        main_nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        # So docker receives the logs as well:
        stdout:
            type: fingers_crossed
            action_level: error
            handler: stdout_nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        stdout_nested:
            type: stream
            path: 'php://stdout'
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
