<?php

declare(strict_types=1);

/*
 * This file is part of the Explicit Architecture POC,
 * which is created on top of the Symfony Demo application.
 *
 * (c) Herberto Graça <herberto.graca@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Acme\PhpExtension\Identity;

/**
 * This can be used for numeric sequential IDs, for example the ones generated by an auto-increment field in an SQL
 * engine. Ideally, however, we would not use such ID generation. Nevertheless it is common to need to use sequential
 * integer IDs, for example for invoices, and we could either use that as a quick and dirty solution or find another
 * way of generating such sequential IDs.
 *
 * This class could be final instead of abstract, and we could have all entities use this same ID class.
 * However, that would have little more benefit than simply having the entities IDs as simple integers, we would still
 * have the ambiguity of "is this value supposed to be the ID of this entity, or is there a mistake and this is some
 * other value?".
 * What we really want to do is to have a specific ID class for each entity, so that we can type hint to specific
 * classes and remove all ambiguity.
 */
abstract class AbstractIntId extends AbstractId
{
    /**
     * @var int
     */
    protected $id;

    /**
     * This constructor is here only to provide the type hint.
     */
    public function __construct(int $id)
    {
        parent::__construct($id);
    }

    public function toScalar(): int
    {
        return $this->id;
    }

    protected function isValid($value): bool
    {
        return \is_int($value) && $value > 0;
    }
}
